# Generated by Django 2.2.4 on 2020-03-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_detail',
            name='user_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
