# Generated by Django 2.2.4 on 2020-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_details',
            name='farmer_id',
            field=models.IntegerField(null=True),
        ),
    ]
