# Generated by Django 2.2.4 on 2020-03-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_details_farmer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking_detail',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Contact_Detail',
        ),
        migrations.DeleteModel(
            name='Booking_Detail',
        ),
    ]
