# Generated by Django 2.2.4 on 2020-03-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200312_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=1000)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Market_Detail')),
            ],
        ),
    ]
