# Generated by Django 2.2.4 on 2020-03-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vegetable_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable_detail',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
