# Generated by Django 2.2.4 on 2020-03-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200312_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vegetable_Detail',
        ),
    ]
