# Generated by Django 2.2.4 on 2020-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_veg_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_detail',
            name='image',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image'),
        ),
    ]
