# Generated by Django 2.2.4 on 2020-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_market_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='veg_detail',
            name='image',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image'),
        ),
    ]
