from django.urls import path
from . import views
urlpatterns = [
path('category/',views.category,name="category"),
path('view/',views.form,name="form"),
path('edit/<int:pk>/',views.catedit,name="catedit"),
path('delete/<int:pk>/',views.catdelete,name="catdelete"),
path('login/',views.login_details,name="login_details"),
path('addproduct/',views.product,name="product"),
path('orderitems/',views.order,name="order"),
path('profile/',views.profile,name="profile"),
path('',views.tem,name="tem"),
path('view_farmer/',views.view_farmer,name="view_farmer"),
path('register/',views.reg,name="reg"),
path('temlogin/',views.login_details,name="login_details"),
path('contact/',views.con,name="con"),
path('user_dashboard/',views.userdash,name="userdash"),
path('view_product/',views.view_product,name="view_product"),
path('product_edit/<int:pk>/',views.product_edit,name="product_edit"),
path('product_delete/<int:pk>/',views.product_delete,name="product_delete"),
path('logout/',views.logout,name="logout"),
path('veg_product/',views.veg_product,name="veg_product"),
path('add_to_cart/<int:pk>/',views.add_to_cart,name="add_to_cart"),
path('cart/',views.cart,name="cart"),
path('view_items_cart/<int:pk>/',views.view_items_cart,name="view_items_cart"),
path('payment_received/<int:pk>/',views.payment_received,name="payment_received"),
path('purchased/',views.purchased,name="purchased"),
path('ordered_item/',views.ordered_item,name="ordered_item"),
path('view_items_cart_product/',views.view_items_cart_product,name="view_items_cart_product"),
path('remove_item/<int:pk>/',views.remove_item,name="remove_item"),
path('purchase/',views.purchase,name="purchase"),
path('purchased_item/<str:pk>/<str:status>/',views.purchased_item,name="purchased_item"),
path('order_item/',views.order_item,name="order_item"),
path('status_order/<str:pk>/<int:user_id>/<str:status>/',views.status_order,name="status_order"),
path('order_item_user/',views.order_item_user,name="order_item_user"),
path('farmer_login/',views.farmer_login,name="farmer_login"),
path('product_list/',views.product_list,name="product_list"),
path('search_market/',views.search_market,name="search_market"),
path('veg_details/<int:pk>/',views.veg_details,name="veg_details"),
path('search/',views.search,name="search"),
]


